import Component from '@glimmer/component';

export default class BoxInsertComponent extends Component {
    deck = {
        "id": 1468807,
        "keyforgeId": "a782a7e4-a981-446f-ab0c-790a7b11b8fe",
        "expansion": "WORLDS_COLLIDE",
        "name": "“Tank”, avocat de Luckcity",
        "creatureCount": 23,
        "actionCount": 10,
        "artifactCount": 1,
        "upgradeCount": 2,
        "registered": true,
        "powerLevel": 0,
        "chains": 0,
        "wins": 1,
        "losses": 2,
        "crucibleTrackerWins": null,
        "crucibleTrackerLosses": null,
        "expectedAmber": 17.143749999999997,
        "amberControl": 4.71875,
        "creatureControl": 11.8625,
        "artifactControl": 1.8125,
        "efficiency": 4.25,
        "effectivePower": 106,
        "amberProtection": 0.5,
        "disruption": 7.125,
        "houseCheating": 0.875,
        "other": 0.0,
        "aercScore": 62.0,
        "previousSasRating": 68,
        "sasRating": 67,
        "synergyRating": 7,
        "antisynergyRating": 2,
        "totalPower": 66,
        "cardDrawCount": 0,
        "cardArchiveCount": 0,
        "keyCheatCount": 0,
        "rawAmber": 8,
        "totalArmor": 3,
        "forSale": false,
        "forTrade": false,
        "forAuction": false,
        "wishlistCount": 0,
        "funnyCount": 0,
        "lastSasUpdate": "2020-02-28",
        "sasPercentile": 76.9009041126181,
        "searchResultCards": [],
        "houses": [
            "Dis",
            "Untamed",
            "StarAlliance"
        ],
        "deckSaleInfo": null,
        "owners": null,
        "synergies": null
    };
}